#!/usr/bin/env ruby

require_relative "../config/environment"

DemoScenarioCatalog.all.each do |scenario|
  conversation = DemoScenarioSeedService.new(slug: scenario[:slug]).call
  puts "#{scenario[:title]} -> /admin/conversations/#{conversation.id}"
end
